### ISSUE TITLE
x86 nas docker 无法开始学习 提示playwright安装失败

### ISSUE THREAD

**Issue by gwd0715** [johIanse/study_xxqg#1]
![telegram-cloud-photo-size-5-6318671966965445374-y](https://user-images.githubusercontent.com/17922721/220832882-ee23e717-c709-4d08-b036-d78f60ad667b.jpg)
请问大佬这个怎么解决啊？

**Comment by johIanse** [comment]
手动装或者重装 具体看教程链接
