### ISSUE TITLE
查询积分显示为0

### ISSUE THREAD

**Issue by huyun0** [johIanse/study_xxqg#3]
虚拟机Docker 运行。同一个docker环境，挂了多账号（一般为8个），刷题都正常，手机端能够看到分数。但网页端查询，有的查询积分为0，也有的查询为正常分值，比如30，35，40等。
![image](https://user-images.githubusercontent.com/27984520/221805495-4a67c07d-811b-4ac2-96e8-94959800c384.png)

**Comment by johIanse** [comment]
按照docker上的说明更新
